ALTER TABLE comprobantes ADD COLUMN categoria_ganancias INTEGER;
ALTER TABLE comprobantes ADD COLUMN pct_afectado REAL NOT NULL DEFAULT 100;
ALTER TABLE bienes_uso ADD COLUMN pct_afectado REAL NOT NULL DEFAULT 100;
ALTER TABLE bienes_uso ADD COLUMN fecha_baja TEXT;
ALTER TABLE bienes_uso ADD COLUMN valor_baja REAL;
CREATE TABLE quebrantos (id INTEGER PRIMARY KEY AUTOINCREMENT, anio_origen INTEGER NOT NULL, categoria INTEGER NOT NULL DEFAULT 3, monto REAL NOT NULL, usado REAL NOT NULL DEFAULT 0);
CREATE TABLE deducciones_generales (id INTEGER PRIMARY KEY AUTOINCREMENT, anio INTEGER NOT NULL, concepto TEXT NOT NULL, monto REAL NOT NULL, notas TEXT);
CREATE TABLE config_personal (anio INTEGER PRIMARY KEY, conyuge INTEGER NOT NULL DEFAULT 0, hijos INTEGER NOT NULL DEFAULT 0, hijos_incapacitados INTEGER NOT NULL DEFAULT 0, ded_especial TEXT NOT NULL DEFAULT 'ninguna');
CREATE TABLE ajustes_anuales (anio INTEGER PRIMARY KEY, ajuste_existencias REAL NOT NULL DEFAULT 0, ajuste_inflacion REAL NOT NULL DEFAULT 0, ingresos_1ra REAL NOT NULL DEFAULT 0, gastos_1ra REAL NOT NULL DEFAULT 0, presuncion_1ra_pct REAL, neto_2da REAL NOT NULL DEFAULT 0, neto_4ta REAL NOT NULL DEFAULT 0, cedular REAL NOT NULL DEFAULT 0, anticipos REAL NOT NULL DEFAULT 0, deb_cred REAL NOT NULL DEFAULT 0, saldo_favor REAL NOT NULL DEFAULT 0);
