name = "simulador-ganancias-api"
main = "src/index.ts"
compatibility_date = "2026-09-01"

[[d1_databases]]
binding = "DB"
database_name = "simulador-ganancias"
database_id = "65b982d2-b983-46c1-a6f8-712e6e5ed959"
migrations_dir = "../../db/migrations"

[vars]
# CUIT propio: se usa para distinguir comprador/vendedor en las liquidaciones
CUIT_PROPIO = "20184558131"
[assets]
directory = "./public"
